name: 'Build and Deploy Image'
on:
  push:
    tags:
      - '*'
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to deploy'
        required: true
        default: 'main'
      environment:
        description: 'Environment to deploy to'
        required: true
        default: 'test'
      tag:
        description: 'Tag to deploy'
        required: true
        default: 'latest'

jobs:
  build-image:    
    runs-on: ubuntu-latest
    permissions: write-all
    environment: build
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Login to production registry
        uses: docker/login-action@v3
        with:
          registry: "${{ vars.REGISTRY }}"
          username: "${{ vars.REGISTRY_USERNAME }}"
          password: "${{ secrets.REGISTRY_PASSWORD }}"
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ vars.REGISTRY }}/${{ vars.APP_NAME }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: build and push to container registry
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
            
  deploy-image-test:
    needs: build-image
    runs-on: 
      group: nomad
    permissions: read-all
    environment: test
    env:
      NOMAD_ADDR: ${{ vars.NOMAD_ADDR }}
      NOMAD_TOKEN: ${{ secrets.NOMAD_TOKEN }}
      NOMAD_SKIP_VERIFY: true
      NOMAD_VAR_NOMAD_DATACENTER: "hqtest"
      NOMAD_VAR_REGISTRY_SERVER: ${{ vars.REGISTRY }}
      NOMAD_VAR_REGISTRY_USERNAME: ${{ vars.REGISTRY_USERNAME }}
      NOMAD_VAR_REGISTRY_PASSWORD: ${{ secrets.REGISTRY_PASSWORD }}
      NOMAD_VAR_FLASK_ENV: "test"
      NOMAD_VAR_APP_NAME: ${{ vars.APP_NAME }}
      NOMAD_VAR_IMAGE_TAG: ${{ vars.REGISTRY}}/${{ vars.APP_NAME }}:${{ github.ref_name }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Validate Jobspec
        run: nomad validate jobspecs/${{vars.APP_NAME}}.hcl
      - name: Run Nomad Plan on JobSpec
        run: echo "APPLY_STRING=$(nomad job plan -no-color jobspecs/${{vars.APP_NAME}}.hcl | tee /dev/stderr | grep '^nomad')" >> $GITHUB_OUTPUT
        id: nomad_plan
      - name: Run Nomad Apply on JobSpec if there are changes
        run: ${{ steps.nomad_plan.outputs.APPLY_STRING }}

  deploy-image-prod:
    needs: deploy-image-test
    runs-on: 
      group: nomad
    permissions: read-all
    environment: production
    env:
      NOMAD_ADDR: ${{ vars.NOMAD_ADDR }}
      NOMAD_TOKEN: ${{ secrets.NOMAD_TOKEN }}
      NOMAD_SKIP_VERIFY: true
      NOMAD_VAR_NOMAD_DATACENTER: "hqprod"
      NOMAD_VAR_REGISTRY_SERVER: ${{ vars.REGISTRY }}
      NOMAD_VAR_REGISTRY_USERNAME: ${{ vars.REGISTRY_USERNAME }}
      NOMAD_VAR_REGISTRY_PASSWORD: ${{ secrets.REGISTRY_PASSWORD }}
      NOMAD_VAR_FLASK_ENV: "production"
      NOMAD_VAR_APP_NAME: ${{ vars.APP_NAME }}
      NOMAD_VAR_IMAGE_TAG: ${{ vars.REGISTRY}}/${{ vars.APP_NAME }}:${{ github.ref_name }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Validate Jobspec
        run: nomad validate jobspecs/${{vars.APP_NAME}}.hcl
      - name: Run Nomad Plan on JobSpec
        run: echo "APPLY_STRING=$(nomad job plan -no-color jobspecs/${{vars.APP_NAME}}.hcl | tee /dev/stderr | grep '^nomad')" >> $GITHUB_OUTPUT
        id: nomad_plan
      - name: Run Nomad Apply on JobSpec if there are changes
        run: ${{ steps.nomad_plan.outputs.APPLY_STRING }}