name: 'Deploy Image'
on:
  push:
    branches:
      - main
    paths-ignore:
      - 'app/*'
      - 'Dockerfile'
      - 'config.py'
      - '.github/*'
      - 'requirements.txt'

env:
    BUILD_IMG: usva1nprdidpacr01.azurecr.io/${{ vars.APP_NAME }}:${{ github.ref_name }}
    
jobs:
  deploy-image-test:
    runs-on: 
      group: nomad
    permissions: read-all
    environment: test
    env:
      NOMAD_ADDR: ${{ vars.NOMAD_ADDR }}
      NOMAD_TOKEN: ${{ secrets.NOMAD_TOKEN }}
      NOMAD_VAR_REGISTRY: usva1nprdidpacr01.azurecr.io
      NOMAD_SKIP_VERIFY: true
      NOMAD_VAR_NOMAD_DATACENTER: "hqtest"
      NOMAD_VAR_FLASK_ENV: "test"
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Validate Jobspec
        run: nomad validate jobspecs/templateapp.hcl
      - name: Run Nomad Plan on JobSpec
        run: echo "APPLY_STRING=$(nomad job plan -no-color jobspecs/templateapp.hcl | tee /dev/stderr | grep '^nomad')" >> $GITHUB_OUTPUT
        id: nomad_plan
      - name: Run Nomad Apply on JobSpec if there are changes
        run: ${{ steps.nomad_plan.outputs.APPLY_STRING }}

  deploy-image-prod:
    needs: deploy-image-test
    runs-on: 
      group: nomad
    permissions: read-all
    environment: production
    env:
      NOMAD_ADDR: ${{ vars.NOMAD_ADDR }}
      NOMAD_TOKEN: ${{ secrets.NOMAD_TOKEN }}
      NOMAD_SKIP_VERIFY: true
      NOMAD_VAR_NOMAD_DATACENTER: "hqtest"
      NOMAD_VAR_NEXUS_USERNAME: ${{ vars.NEXUS_USERNAME }}
      NOMAD_VAR_NEXUS_PASSWORD: ${{ secrets.NEXUS_PASSWORD }}
      NOMAD_VAR_FLASK_ENV: "test"
      NOMAD_VAR_DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
    # container:
    #   image: nexusdocker.testapps.usoil.local/repository/usv-docker/usv-corporate-apps/cicd:main
    #   credentials:
    #     username: ${{ vars.NEXUS_USERNAME }}
    #     password: ${{ secrets.NEXUS_PASSWORD }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Validate Jobspec
        run: nomad validate jobspecs/templateapp.hcl
      - name: Run Nomad Plan on JobSpec
        run: echo "APPLY_STRING=$(nomad job plan -no-color jobspecs/templateapp.hcl | tee /dev/stderr | grep '^nomad')" >> $GITHUB_OUTPUT
        id: nomad_plan
      - name: Run Nomad Apply on JobSpec if there are changes
        run: ${{ steps.nomad_plan.outputs.APPLY_STRING }}