name: 'Deploy Image'
on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to deploy'
        required: true
        default: 'main'
      environment:
        description: 'Environment to deploy to'
        required: true
        default: 'test'
      tag:
        description: 'Tag to deploy'
        required: true
        default: 'latest'
    
jobs:
  deploy-image-test:
    runs-on: 
      group: nomad
    permissions: read-all
    environment: test
    env:
      NOMAD_ADDR: ${{ vars.NOMAD_ADDR }}
      NOMAD_TOKEN: ${{ secrets.NOMAD_TOKEN }}
      NOMAD_SKIP_VERIFY: true
      NOMAD_VAR_NOMAD_DATACENTER: "hqtest"
      NOMAD_VAR_REGISTRY_SERVER: ${{ vars.REGISTRY }}
      NOMAD_VAR_REGISTRY_USERNAME: ${{ vars.REGISTRY_USERNAME }}
      NOMAD_VAR_REGISTRY_PASSWORD: ${{ secrets.REGISTRY_PASSWORD }}
      NOMAD_VAR_FLASK_ENV: "test"
      NOMAD_VAR_APP_NAME: ${{ vars.APP_NAME }}
      NOMAD_VAR_IMAGE_TAG: ${{ vars.REGISTRY }}/${{ vars.APP_NAME }}:${{ github.ref_name }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Validate Jobspec
        run: nomad validate jobspecs/${{vars.APP_NAME}}.hcl
      - name: Run Nomad Plan on JobSpec
        run: echo "APPLY_STRING=$(nomad job plan -no-color jobspecs/${{vars.APP_NAME}}.hcl | tee /dev/stderr | grep '^nomad')" >> $GITHUB_OUTPUT
        id: nomad_plan
      - name: Run Nomad Apply on JobSpec if there are changes
        run: ${{ steps.nomad_plan.outputs.APPLY_STRING }}

  deploy-image-prod:
    needs: deploy-image-test
    runs-on: 
      group: nomad
    permissions: read-all
    environment: production
    env:
      NOMAD_ADDR: ${{ vars.NOMAD_ADDR }}
      NOMAD_TOKEN: ${{ secrets.NOMAD_TOKEN }}
      NOMAD_SKIP_VERIFY: true
      NOMAD_VAR_NOMAD_DATACENTER: "hqprod"
      NOMAD_VAR_REGISTRY_SERVER: ${{ vars.REGISTRY }}
      NOMAD_VAR_REGISTRY_USERNAME: ${{ vars.REGISTRY_USERNAME }}
      NOMAD_VAR_REGISTRY_PASSWORD: ${{ secrets.REGISTRY_PASSWORD }}
      NOMAD_VAR_FLASK_ENV: "production"
      NOMAD_VAR_APP_NAME: ${{ vars.APP_NAME }}
      NOMAD_VAR_IMAGE_TAG: ${{ vars.REGISTRY}}/${{ vars.APP_NAME }}:${{ github.ref_name }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Validate Jobspec
        run: nomad validate jobspecs/${{vars.APP_NAME}}.hcl
      - name: Run Nomad Plan on JobSpec
        run: echo "APPLY_STRING=$(nomad job plan -no-color jobspecs/${{vars.APP_NAME}}.hcl | tee /dev/stderr | grep '^nomad')" >> $GITHUB_OUTPUT
        id: nomad_plan
      - name: Run Nomad Apply on JobSpec if there are changes
        run: ${{ steps.nomad_plan.outputs.APPLY_STRING }}